# -*- coding: utf-8 -*-
"""fbprophet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DDat3EZ8ootrz9hL0_aYc_DeuxHTZs9Y
"""

pip install yfinance

pip install streamlit

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import datetime as dt
import pandas_datareader.data as reader
import yfinance as yf
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.layers import Dense,Dropout,LSTM
from tensorflow.keras.models import Sequential
from fbprophet import Prophet

# Setting inicial

crypro_currency=input("Enter the Currency :")
against_currency=input("Which Currecy Do you want to use for reference : ")

x=crypro_currency+"-"+against_currency
print(x)
type(x)

start=dt.datetime(2016,1,1)
end=dt.datetime.now()
data = yf.download(x,start,end)

# How The Data Looks
data.head()

data.info()

model=Prophet(interval_width=0.95, daily_seasonality=True)
df=data.reset_index()
df
df[['ds','y']]=df[['Date','Adj Close']]
model.fit(df)

df

df.info()

future=model.make_future_dataframe(periods=100,freq='D')

forecast=model.predict(future)

forecast.head()

model.plot(forecast)

future = model.make_future_dataframe(periods=100,freq='D')
forecast = model.predict(future)
forecast.tail()

model.plot(forecast)

model.plot_components(forecast)

from fbprophet.diagnostics import cross_validation
df_cv = cross_validation(model, initial='1000 days', period='1000 days', horizon = '500 days')
df_cv.head()

from fbprophet.diagnostics import performance_metrics
df_p = performance_metrics(df_cv)
df_p.head()

df_p.head()

from fbprophet.plot import plot_cross_validation_metric
fig = plot_cross_validation_metric(df_cv, metric='mape')

